# Generated by Django 5.2.1 on 2026-01-30 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meeting_file',
            field=models.FileField(blank=True, null=True, upload_to='meetings/'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='ai_output',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_type',
            field=models.CharField(choices=[('team', 'Team'), ('client', 'Client'), ('interview', 'Interview'), ('standup', 'Standup')], max_length=20),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='transcript',
            field=models.TextField(blank=True, null=True),
        ),
    ]
