# Generated by Django 5.2.1 on 2026-01-30 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_meeting_meeting_file_alter_meeting_ai_output_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='google_meet_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
